// import { Food } from "./app/shared/models/Food";
// import { Tag } from "./app/shared/models/Tag";

// In the Begining Change Food[] to any[] && Tag[] to any[]
export const sampleFoods: any[] = [
  {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 299,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'https://media.istockphoto.com/id/1181651561/photo/oven-baked-pepperoni-pizza.jpg?b=1&s=170667a&w=0&k=20&c=rXZuTnWkNeYlm5ploNg2bMixLsC6n8dhg6Lpfq3hj98=',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'2',
    name: 'Sushi',
    price: 999,
    cookTime: '35-45',
    favorite: true,
    origins: ['Japan'],
    stars: 5.0,
    imageUrl: 'https://www.holidify.com/images/cmsuploads/compressed/c700x420_20181227132950.jpg',
    tags: ['Lunch', 'Dinner'],
  },
  {
    id:'3',
    name: 'Kebab',
    price: 799,
    cookTime: '35-45',
    favorite: true,
    origins: ['Turkey'],
    stars: 4.0,
    imageUrl: 'https://www.holidify.com/images/cmsuploads/compressed/bacon-kebabs-13-2_20181227133457.jpg',
    tags: ['Lunch', 'Dinner'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 50,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'https://www.seriouseats.com/thmb/X42-ZmDHc9V2cRZEgKJ4Wh6vGjs=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20211201-crispy-roasted-potatoes-vicky-wasik-45-d75608ce325e4ffbab665084eba642c8.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 259,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'https://media.istockphoto.com/id/157741415/photo/homemade-turkey-soup.jpg?s=612x612&w=0&k=20&c=wrnPdlS02lfg4Bg6l8G17IMzxRl_nMZFQhKw6yLXVBw=',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 159,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'https://c4.wallpaperflare.com/wallpaper/786/792/888/veggie-pizza-pizza-and-red-pepper-wallpaper-preview.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'7',
    name: 'Meatball',
    price: 399,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'https://wallpaperaccess.com/full/4008494.jpg',
    tags: ['SlowFood', 'Lunch', 'Dinner'],
  },
  {
    id:'8',
    name: 'Rendang',
    price: 599,
    cookTime: '50-60',
    favorite: false,
    origins: ['Indonesia'],
    stars: 4.5,
    imageUrl: 'https://www.holidify.com/images/cmsuploads/compressed/8896564-16x9-large_20181227133052.jpg',
    tags: ['Lunch', 'Dinner'],
  },
  {
    id:'9',
    name: 'Ramen',
    price: 399,
    cookTime: '15-20',
    favorite: true,
    origins: ['Japan'],
    stars: 5.0,
    imageUrl: 'https://www.holidify.com/images/cmsuploads/compressed/shoyu-ramen_20181227133143.jpg',
    tags: ['FastFood', 'Lunch'],
  },
  {
    id:'10',
    name: 'Tom Yam Goong',
    price: 699,
    cookTime: '55-65',
    favorite: true,
    origins: ['Thailand'],
    stars: 4.0,
    imageUrl: 'https://www.holidify.com/images/cmsuploads/compressed/R00067_Tom-Yum-Goong_20181227133333.jpg',
    tags: ['Lunch', 'Dinner'],
  },
  {
    id:'11',
    name: 'Hamburger',
    price: 100,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'https://images2.alphacoders.com/276/276352.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'12',
    name: 'Pho',
    price: 359,
    cookTime: '55-65',
    favorite: true,
    origins: ['Vietnam'],
    stars: 3.5,
    imageUrl: 'https://www.holidify.com/images/cmsuploads/compressed/wmkj5fafebzkxpwhuzg6_20181227133752.jpeg',
    tags: ['Lunch', 'Dinner'],
  },
  {
    id:'13',
    name: 'Peking duck',
    price: 999,
    cookTime: '55-65',
    favorite: false,
    origins: ['China'],
    stars: 4.0,
    imageUrl: 'https://www.holidify.com/images/cmsuploads/compressed/peking-duck-10916-1_20181227133910.jpg',
    tags: ['Lunch', 'Dinner'],
  },
  {
    id:'14',
    name: 'Paella',
    price: 1099,
    cookTime: '25-35',
    favorite: true,
    origins: ['Spain'],
    stars: 5.0,
    imageUrl: 'https://www.holidify.com/images/cmsuploads/compressed/mixed-seafood-paella_20181227133958.jpeg',
    tags: ['Lunch', 'Dinner'],
  },
  {
    id:'15',
    name: 'Steak and Kidney Pie',
    price: 1299,
    cookTime: '55-65',
    favorite: true,
    origins: ['England'],
    stars: 4.5,
    imageUrl: 'https://www.holidify.com/images/cmsuploads/compressed/steakandkidneypie_73308_16x9_20181227134043.jpg',
    tags: ['Lunch', 'Dinner'],
  },
  {
    id:'16',
    name: 'Apfelstrudel',
    price: 299,
    cookTime: '45-55',
    favorite: true,
    origins: ['Austria'],
    stars: 4.0,
    imageUrl: 'https://www.holidify.com/images/cmsuploads/compressed/48824979_20181227134147.jpg',
    tags: ['FastFood', 'Lunch'],
  },
  {
    id:'17',
    name: 'Pad Thai',
    price: 259,
    cookTime: '20-30',
    favorite: true,
    origins: ['Thailand'],
    stars: 4.5,
    imageUrl: 'https://www.holidify.com/images/cmsuploads/compressed/28COOKING-PAD-THAI1-videoSixteenByNineJumbo1600_20181227134239.jpg',
    tags: ['Lunch', 'Dinner'],
  },
  {
    id:'18',
    name: 'Goulash',
    price: 899,
    cookTime: '50-65',
    favorite: false,
    origins: ['Hungary'],
    stars: 5.0,
    imageUrl: 'https://www.holidify.com/images/cmsuploads/compressed/20160205-beef-goulash-hungarian-recipe-food-lab-26_20181227134326.jpg',
    tags: ['Lunch', 'Dinner'],
  },
  {
    id:'19',
    name: 'Lasagna',
    price: 399,
    cookTime: '15-25',
    favorite: true,
    origins: ['Italy'],
    stars: 4.0,
    imageUrl: 'https://www.holidify.com/images/cmsuploads/compressed/9dd2e32b-613d-4515-9597-39ba6ad86b8b_20181227134422.jpg',
    tags: ['FastFood', 'Lunch'],
  },
  {
    id:'20',
    name: 'Kimchi',
    price: 499,
    cookTime: '35-45',
    favorite: true,
    origins: ['Korea'],
    stars: 4.0,
    imageUrl: 'https://www.holidify.com/images/cmsuploads/compressed/Kimchi-5_20181227134514.jpg',
    tags: ['Lunch', 'Dinner'],
  },
];

// To Get the Tags for Food
// In the Begining Change Food[] to any[] && Tag[] to any[]
export const sampleTags: any[] = [
  { name: 'Pizza', count: 2 },
  { name: 'FastFood', count: 7 },
  { name: 'SlowFood', count: 2 },
  { name: 'Lunch', count: 17 },
  { name: 'Dinner', count: 12 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
  { name: 'Hamburger', count: 1 },
];

// Users Array
// sample Users to test the Api
export const sampleUsers: any[] = [
  { 
    name: 'Vinay',
    email: 'test@gmail.com', 
    password: '123456', 
    address: 'L.A', 
    isAdmin: true 
  },
  { 
    name: 'VinayC', 
    email: 'test2@gmail.com', 
    password: '123456', 
    address: 'NYC', 
    isAdmin: false 
  },
];